[project]
name = 'property-title-registry'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.property-registry]
path = 'contracts/property-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.title-verification]
path = 'contracts/title-verification.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
